[package]
name = "stopper"
version = "0.1.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"
description = "an async stop broadcaster or something like that"

[dependencies]
waker-set = "0.1.1"
futures-lite = "1.11.3"
pin-project = "1.0.5"
