[package]
name = "stopper"
version = "0.2.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"
description = "an async stream and future stopper mechanism"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/jbr/stopper"

[dependencies]
waker-set = "0.2.0"
futures-lite = "1.11.3"
pin-project = "1.0.5"

[dev-dependencies]
async-io = "1.3.1"
